name: Build & Release Binaries

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64]
        # if you want native M1:
        # arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      # 3. Setup Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 4. Build Go binary
      - name: Build Go
        run: |
          set -eux
          cd go
          go mod tidy
          GOOS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          GOARCH=${{ matrix.arch }}
          go build -v -o ../yaml2json-go-${GOOS}-${GOARCH}
          cd ..

      # 5. Build Rust binary
      - name: Build Rust
        run: |
          set -eux
          cd rust
          cargo build --release
          cp target/release/yaml2json-rust ../yaml2json-rust-${{ runner.os }}-${{ matrix.arch }}
          cd ..

      # 6. Prepare artifacts
      - name: Prepare artifacts
        run: |
          set -eux
          mkdir -p artifacts
          mv yaml2json-go-* artifacts/
          mv yaml2json-rust-* artifacts/
          sha256sum artifacts/* > artifacts/checksums.txt || shasum -a 256 artifacts/* > artifacts/checksums.txt
          ls -lah artifacts

      # 7. Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      # 8. Upload binaries to Release
      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
